# Data Analytics

## Numerical Python (NumPy) 

Una de las estructuras de datos más importantes es el <font color = 'blue'>array</font>. Los <font color = 'blue'>arrays</font> estructuran otros objetos <font color = 'red'>del mismo tipo</font> en filas y columnas. 

Un <font color = 'blue'>array</font> de una sola dimensión se conoce como un <font color = 'green'>vector</font>. Lo cual significa que solo contiene una sola columna o fila de elementos. Sin embargo, los <font color = 'blue'>arrays</font> pueden generalizarse para convertirse en matrices de i x j elementos (2 dimensiones). Y posteriormente más dimensiones i x j x n... etc. 

La librería NumPy tiene una clase especial de objeto conocido como <font color = 'blue'>ndarray</font>. 

In [2]:
import numpy as np   # Importando la librería numpy, con la abreviatura "np"


In [3]:
a = [0.5, 0.75, 1.0, 1.5, 2.0]   # Creando un list

In [4]:
a                    # Un list de una sola dimensión

[0.5, 0.75, 1.0, 1.5, 2.0]

In [5]:
b = [a, a, a]        # Combinando una serie de objetos, se crea una matriz de números

In [6]:
b              

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
b[1][0]             # Para accesar indizando una matriz, debo utilizar doble indizado

0.5

In [15]:
b[1][0]  = 1
b

[[1, 0.75, 1.0, 1.5, 2.0], [1, 0.75, 1.0, 1.5, 2.0], [1, 0.75, 1.0, 1.5, 2.0]]

In [16]:
c = [5, 10, 15]      # Creo un list
d = [3, 6, 9]        # Creo un segundo list
e = [c, d]           # Creo un objeto de 2 dimensiones
f = [e, e]           # Creo un objeto de 3 dimensiones

In [23]:
f[0][1][2]

9

In [18]:
f[1][1][0]          # Triple indizado

[[[5, 10, 15], [3, 6, 9]], [[5, 10, 15], [3, 6, 9]]]

Existen diversas formas de crear <font color = 'blue'>arrays</font> a partir de lists. Pero las lists son para propósitos más generales. Los <font color = 'blue'>arrays</font> son más especializados, y NumPy nos presenta una clase especial de array que es bastante flexible y eficiente: <font color = 'blue'>numpy.darray class</font>.

In [24]:
g = np.array([0, 3, 6, 9, 12])  # np.array para crear un numpy.darray
type(g)

numpy.ndarray

In [26]:
g[2:]    # Slicing con numpy.darray

array([ 6,  9, 12])

In [25]:
g[:3]    # Ejem 2 slicing

array([0, 3, 6])

In [27]:
sum(g)

30

In [ ]:
g.sum()  # Este objeto contiene una gran multitud de métodos

30

In [28]:
g.std()  # Desviación estándar

4.242640687119285

In [29]:
g * 2    # Multiplica el array por 2

array([ 0,  6, 12, 18, 24])

In [31]:
h = np.array([g, g*3])  # Los ndarray también pueden ser de múltiples dimensiones

In [30]:
g + g

array([ 0,  6, 12, 18, 24])

**Ventajas de los NumPy arrays (especializados):** 
* Tiene dimensiones por defecto (ejes)
* Son de tamaño inmutable
* Permite solamente un tipo de objeto 